package com.upuphone.starrynet.core.ble.channel;

public enum ChannelEvent {
    RECV_CTR,
    SEND_CTR,
    RECV_DATA,
    SEND_DATA,
    RECV_ACK,
    SEND_ACK,
    RECV_SINGLE_CTR,
    SEND_SINGLE_CTR,
    RECV_SINGLE_ACK,
    SEND_SINGLE_ACK,
    RECV_MNG,
    SEND_MNG,
    RECV_MNG_ACK,
    SEND_MNG_ACK,
    SEND_FAST_CTR,
    RECEIVE_FAST_CTR,
    RECEIVE_FAST_ACK,
    SEND_FAST_ACK,
    RECV_FAST_DATA,
    RECEIVE_MIX_CTR,
    RECV_MIX_DATA,
    SEND_SINGLE_CMD_NO_ACK,
    RECEIVE_SINGLE_CMD_NO_ACK
}
