package com.here.odnp.gnss;

public class GnssObservationData {
    public static final int ACC_DELTA_RANGE_STATE_CYCLE_SLIP = 4;
    public static final int ACC_DELTA_RANGE_STATE_HALF_CYCLE_REPORTED = 16;
    public static final int ACC_DELTA_RANGE_STATE_HALF_CYCLE_RESOLVED = 8;
    public static final int ACC_DELTA_RANGE_STATE_RESET = 2;
    public static final int ACC_DELTA_RANGE_STATE_UNKNOWN = 0;
    public static final int ACC_DELTA_RANGE_STATE_VALID = 1;
    public static final int MULTIPATH_INDICATOR_DETECTED = 1;
    public static final int MULTIPATH_INDICATOR_NOT_DETECTED = 2;
    public static final int MULTIPATH_INDICATOR_UNKNOWN = 0;
    public static final int SATELLITE_STATE_BDS_D2_BIT_SYNC = 256;
    public static final int SATELLITE_STATE_BDS_D2_SUBFRAME_SYNC = 512;
    public static final int SATELLITE_STATE_BIT_SYNC = 2;
    public static final int SATELLITE_STATE_CODE_LOCK = 1;
    public static final int SATELLITE_STATE_GAL_E1BC_CODE_LOCK = 1024;
    public static final int SATELLITE_STATE_GAL_E1B_PAGE_SYNC = 4096;
    public static final int SATELLITE_STATE_GAL_E1C_2ND_CODE_LOCK = 2048;
    public static final int SATELLITE_STATE_GLO_STRING_SYNC = 64;
    public static final int SATELLITE_STATE_GLO_TOD_DECODED = 128;
    public static final int SATELLITE_STATE_GLO_TOD_KNOWN = 32768;
    public static final int SATELLITE_STATE_MSEC_AMBIGUOUS = 16;
    public static final int SATELLITE_STATE_SBAS_SYNC = 8192;
    public static final int SATELLITE_STATE_SUBFRAME_SYNC = 4;
    public static final int SATELLITE_STATE_SYMBOL_SYNC = 32;
    public static final int SATELLITE_STATE_TOW_DECODED = 8;
    public static final int SATELLITE_STATE_TOW_KNOWN = 16384;
    public static final int SATELLITE_STATE_UNKNOWN = 0;
    public double accumulatedDeltaRangeMeters;
    public double accumulatedDeltaRangeMetersUncertainty;
    public int accumulatedDeltaRangeState;
    public double automaticGainControlLevelDb;
    public float carrierFrequencyHz;
    public double cn0DbHz;
    public int constellationType;
    public boolean hasAutomaticGainControlLevelDb;
    public boolean hasCarrierFrequencyHz;
    public boolean hasSnrInDb;
    public int multipathIndicator;
    public double pseudorangeRateMetersPerSecond;
    public double pseudorangeRateMetersPerSecondUncertainty;
    public long receivedSvTimeNanos;
    public long receivedSvTimeNanosUncertainty;
    public double snrInDb;
    public int state;
    public int svId;
    public double timeOffsetNanos;
}
