package com.here.sdk.routing;

public enum ManeuverAction {
    DEPART(0),
    ARRIVE(1),
    LEFT_U_TURN(2),
    SHARP_LEFT_TURN(3),
    LEFT_TURN(4),
    SLIGHT_LEFT_TURN(5),
    CONTINUE_ON(6),
    SLIGHT_RIGHT_TURN(7),
    RIGHT_TURN(8),
    SHARP_RIGHT_TURN(9),
    RIGHT_U_TURN(10),
    LEFT_EXIT(11),
    RIGHT_EXIT(12),
    LEFT_RAMP(13),
    RIGHT_RAMP(14),
    LEFT_FORK(15),
    MIDDLE_FORK(16),
    RIGHT_FORK(17),
    ENTER_HIGHWAY_FROM_LEFT(18),
    ENTER_HIGHWAY_FROM_RIGHT(19),
    LEFT_ROUNDABOUT_ENTER(20),
    RIGHT_ROUNDABOUT_ENTER(21),
    LEFT_ROUNDABOUT_PASS(22),
    RIGHT_ROUNDABOUT_PASS(23),
    LEFT_ROUNDABOUT_EXIT1(24),
    LEFT_ROUNDABOUT_EXIT2(25),
    LEFT_ROUNDABOUT_EXIT3(26),
    LEFT_ROUNDABOUT_EXIT4(27),
    LEFT_ROUNDABOUT_EXIT5(28),
    LEFT_ROUNDABOUT_EXIT6(29),
    LEFT_ROUNDABOUT_EXIT7(30),
    LEFT_ROUNDABOUT_EXIT8(31),
    LEFT_ROUNDABOUT_EXIT9(32),
    LEFT_ROUNDABOUT_EXIT10(33),
    LEFT_ROUNDABOUT_EXIT11(34),
    LEFT_ROUNDABOUT_EXIT12(35),
    RIGHT_ROUNDABOUT_EXIT1(36),
    RIGHT_ROUNDABOUT_EXIT2(37),
    RIGHT_ROUNDABOUT_EXIT3(38),
    RIGHT_ROUNDABOUT_EXIT4(39),
    RIGHT_ROUNDABOUT_EXIT5(40),
    RIGHT_ROUNDABOUT_EXIT6(41),
    RIGHT_ROUNDABOUT_EXIT7(42),
    RIGHT_ROUNDABOUT_EXIT8(43),
    RIGHT_ROUNDABOUT_EXIT9(44),
    RIGHT_ROUNDABOUT_EXIT10(45),
    RIGHT_ROUNDABOUT_EXIT11(46),
    RIGHT_ROUNDABOUT_EXIT12(47);
    
    public final int value;

    private ManeuverAction(int i) {
        this.value = i;
    }
}
