package com.here.sdk.routing;

public enum RoutingError {
    INTERNAL_ERROR(1),
    INVALID_PARAMETER(2),
    SERVER_UNREACHABLE(3),
    HTTP_ERROR(4),
    AUTHENTICATION_FAILED(5),
    FORBIDDEN(6),
    EXCEEDED_USAGE_LIMIT(7),
    PARSING_ERROR(8),
    NO_ROUTE_FOUND(9),
    TIMED_OUT(10),
    OFFLINE(11),
    NO_ISOLINE_FOUND(12),
    NO_ROUTE_HANDLE(13),
    OPERATION_CANCELLED(14),
    COULD_NOT_MATCH_DESTINATION(15),
    COULD_NOT_MATCH_ORIGIN(16),
    FAILED_ROUTE_HANDLE_CREATION(17),
    IMPORT_FAILED(18),
    NO_REACHABLE_CHARGING_STATION_FOUND(19),
    ROUTE_CALCULATION_FAILED(20),
    ROUTE_LENGTH_LIMIT_EXCEEDED(21),
    VIOLATED_TRANSPORT_MODE_IN_ROUTE_HANDLE_DECODING(22),
    PROXY_AUTHENTICATION_FAILED(23),
    PROXY_SERVER_UNREACHABLE(24);
    
    public final int value;

    private RoutingError(int i) {
        this.value = i;
    }
}
