package com.upuphone.runasone.uupcast;

import android.text.TextUtils;
import java.util.HashMap;
import java.util.Map;

public class CastEventCode {
    private static final Map<Integer, String> EVENT_INFO_MAP;
    public static final String KEY_EVENT_DESC = "CastEventDesc";
    public static final int SINK_AUDIO_FOCUS_GAINED = 79;
    public static final int SINK_AUDIO_FOCUS_LOSS_TRANSIENT = 80;
    public static final int SINK_AUDIO_FOCUS_LOST = 81;
    public static final int SINK_AUDIO_FOCUS_REQUEST_FAILED = 78;
    public static final int SINK_BEGIN_CONNECT_SOURCE = 50;
    public static final int SINK_BEGIN_CREATE_AUDIO_DECODER = 62;
    public static final int SINK_BEGIN_CREATE_AUDIO_TRACK = 60;
    public static final int SINK_BEGIN_CREATE_MEDIA_SERVER = 74;
    public static final int SINK_BEGIN_CREATE_VIDEO_DECODER = 64;
    public static final int SINK_BEGIN_QUIT = 72;
    public static final int SINK_BEGIN_TEAR_DOWN = 70;
    public static final int SINK_CONNECT_SOURCE_SUCCESS = 51;
    public static final int SINK_CREATE_AUDIO_DECODER_SUCCESS = 63;
    public static final int SINK_CREATE_AUDIO_TRACK_SUCCESS = 61;
    public static final int SINK_CREATE_VIDEO_DECODER_SUCCESS = 65;
    public static final int SINK_HANDLE_DESCRIBE_SUCCESS = 53;
    public static final int SINK_HANDLE_PLAY_SUCCESS = 57;
    public static final int SINK_HANDLE_SETUP_SUCCESS = 55;
    public static final int SINK_MEDIA_SERVER_CONNECTED = 75;
    public static final int SINK_PULL_STATISTIC = 76;
    public static final int SINK_QUIT_SUCCESS = 73;
    public static final int SINK_RECEIVE_AUDIO_CONFIG = 58;
    public static final int SINK_RECEIVE_FIRST_AUDIO_FRAME = 66;
    public static final int SINK_RECEIVE_FIRST_VIDEO_FRAME = 68;
    public static final int SINK_RECEIVE_VIDEO_CONFIG = 59;
    public static final int SINK_RENDER_FIRST_AUDIO_FRAME = 67;
    public static final int SINK_RENDER_FIRST_VIDEO_FRAME = 69;
    public static final int SINK_SEND_DESCRIBE = 52;
    public static final int SINK_SEND_PLAY = 56;
    public static final int SINK_SEND_SETUP = 54;
    public static final int SINK_TEAR_DOWN_CONFIRMED = 71;
    public static final int SINK_UIBC_CLIENT_READY = 82;
    public static final int SINK_VIDEO_DECODER_RELEASED = 86;
    public static final int SINK_VIDEO_SIZE_DETERMINED = 77;
    public static final int SINK_VIDEO_SURFACE_CONFIGURABLE = 85;
    public static final int SOURCE_AUDIO_ENCODE_FAIL = 1000;
    public static final int SOURCE_BEGIN_CLOSE_CAMERA = 27;
    public static final int SOURCE_BEGIN_CLOSE_VIRTUAL_DISPLAY = 23;
    public static final int SOURCE_BEGIN_CONNECT_MEDIA_SERVER = 16;
    public static final int SOURCE_BEGIN_CREATE_AUDIO_ENCODER = 10;
    public static final int SOURCE_BEGIN_CREATE_SOCKET_SERVER = 1;
    public static final int SOURCE_BEGIN_CREATE_VIDEO_ENCODER = 12;
    public static final int SOURCE_BEGIN_CREATE_VIRTUAL_DISPLAY = 21;
    public static final int SOURCE_BEGIN_OPEN_CAMERA = 25;
    public static final int SOURCE_BEGIN_OPEN_DUMMY_CAMERA = 37;
    public static final int SOURCE_BEGIN_PAUSE_DUMMY_CAMERA = 39;
    public static final int SOURCE_BEGIN_PUSH_MEDIA = 18;
    public static final int SOURCE_BEGIN_QUIT = 32;
    public static final int SOURCE_BEGIN_RESUME_DUMMY_CAMERA = 40;
    public static final int SOURCE_BEGIN_START_AUDIO_RECORD = 19;
    public static final int SOURCE_BEGIN_STOP_DUMMY_CAMERA = 38;
    public static final int SOURCE_CLOSE_CAMERA_SUCCESS = 28;
    public static final int SOURCE_CLOSE_VIRTUAL_DISPLAY_SUCCESS = 24;
    public static final int SOURCE_CONNECT_BEGIN_QUIT = 101;
    public static final int SOURCE_CONNECT_QUIT_SUCC = 102;
    public static final int SOURCE_CONNECT_SINK_MEDIA_SERVER_SUCCESS = 17;
    public static final int SOURCE_CREATE_AUDIO_CONFIG_SUCCESS = 14;
    public static final int SOURCE_CREATE_AUDIO_ENCODER_SUCCESS = 11;
    public static final int SOURCE_CREATE_SOCKET_SERVER_SUCCESS = 2;
    public static final int SOURCE_CREATE_VIDEO_CONFIG_SUCCESS = 15;
    public static final int SOURCE_CREATE_VIDEO_ENCODER_SUCCESS = 13;
    public static final int SOURCE_CREATE_VIRTUAL_DISPLAY_SUCCESS = 22;
    public static final int SOURCE_HANDLE_DESCRIBE_SUCCESS = 5;
    public static final int SOURCE_HANDLE_PLAY_SUCCESS = 9;
    public static final int SOURCE_HANDLE_SETUP_SUCCESS = 7;
    public static final int SOURCE_MODIFY_VIRTUAL_DISPLAY_SUCCESS = 35;
    public static final int SOURCE_OPEN_CAMERA_SUCCESS = 26;
    public static final int SOURCE_PAUSE_VIRTUAL_DISPLAY_SUCCESS = 83;
    public static final int SOURCE_PUSH_FIRST_AUDIO_SUCCESS = 29;
    public static final int SOURCE_PUSH_FIRST_VIDEO_SUCCESS = 30;
    public static final int SOURCE_PUSH_STATISTIC = 34;
    public static final int SOURCE_QUIT_SUCCESS = 33;
    public static final int SOURCE_RECEIVE_DESCRIBE = 4;
    public static final int SOURCE_RECEIVE_PLAY = 8;
    public static final int SOURCE_RECEIVE_SETUP = 6;
    public static final int SOURCE_RECEIVE_TEAR_DOWN = 31;
    public static final int SOURCE_RESUME_VIRTUAL_DISPLAY_SUCCESS = 84;
    public static final int SOURCE_SHARE_VIRTUAL_DISPLAY_SUCCESS = 36;
    public static final int SOURCE_SOCKET_RECEIVE_SINK_CONNECTION = 3;
    public static final int SOURCE_START_AUDIO_RECORD_SUCCESS = 20;

    static {
        HashMap hashMap = new HashMap();
        EVENT_INFO_MAP = hashMap;
        hashMap.put(1, "Source 端开始创建Socket服务端");
        hashMap.put(2, "Source 端创建Socket服务端成功");
        hashMap.put(3, "Source 端Socket服务收到Sink端连接");
        hashMap.put(4, "Source 端收到describe指令");
        hashMap.put(5, "Source 端处理describe指令成功");
        hashMap.put(6, "Source 端收到setup指令");
        hashMap.put(7, "Source 端处理setup指令成功");
        hashMap.put(8, "Source 端收到play指令");
        hashMap.put(9, "Source 端处理play指令成功");
        hashMap.put(10, "Source 端开始创建音频编码器");
        hashMap.put(11, "Source 端创建音频编码器成功");
        hashMap.put(12, "Source 端开始创建视频编码器");
        hashMap.put(13, "Source 端创建视频编码器成功");
        hashMap.put(14, "Source 端创建音频配置成功");
        hashMap.put(15, "Source 端创建视频配置成功");
        hashMap.put(16, "Source 端开始连接Sink端媒体服务");
        hashMap.put(17, "Source 端连接Sink端媒体服务成功");
        hashMap.put(18, "Source 端开始推流");
        hashMap.put(19, "Source 端开始启动AudioRecord");
        hashMap.put(20, "Source 端启动AudioRecord成功");
        hashMap.put(21, "Source 端开始创建VirtualDisplay");
        hashMap.put(22, "Source 端创建VirtualDisplay成功");
        hashMap.put(23, "Source 端开始关闭VirtualDisplay");
        hashMap.put(24, "Source 端关闭VirtualDisplay成功");
        hashMap.put(25, "Source 端开始打开相机");
        hashMap.put(26, "Source 端打开相机成功");
        hashMap.put(27, "Source 端开始关闭相机");
        hashMap.put(28, "Source 端关闭相机成功");
        hashMap.put(29, "Source 端推送第一帧音频");
        hashMap.put(30, "Source 端推送第一帧视频");
        hashMap.put(31, "Source 端接收到终止投屏指令");
        hashMap.put(32, "Source 端开始退出");
        hashMap.put(33, "Source 端退出结束");
        hashMap.put(34, "Source 端推流数据统计");
        hashMap.put(35, "Source 端成功调整VirtualDisplay");
        hashMap.put(36, "Source 端成功共用已有VirtualDisplay");
        hashMap.put(83, "Source 端暂停VirtualDisplay");
        hashMap.put(84, "Source 端恢复VirtualDisplay");
        hashMap.put(37, "Source 端打开自定义Source");
        hashMap.put(38, "Source 端关闭自定义Source");
        hashMap.put(39, "Source 端暂停自定义Source");
        hashMap.put(40, "Source 端resume自定义Source");
        hashMap.put(1000, "Source 端音频编码失败");
        hashMap.put(101, "Source 端连接开始退出");
        hashMap.put(102, "Source 端连接退出成功");
        hashMap.put(50, "Sink 端开始连接Source端Socket服务");
        hashMap.put(51, "Sink 端连接Source端Socket服务成功");
        hashMap.put(52, "Sink 端发送describe指令");
        hashMap.put(53, "Sink 端处理describe指令成功");
        hashMap.put(54, "Sink 端开始发送setup指令");
        hashMap.put(55, "Sink 端处理setup指令成功");
        hashMap.put(56, "Sink 端发送play指令");
        hashMap.put(57, "Sink 端处理play指令成功");
        hashMap.put(58, "Sink 端接收到音频配置信息");
        hashMap.put(59, "Sink 端接收到视频配置信息");
        hashMap.put(60, "Sink 端开始创建AudioTrack");
        hashMap.put(61, "Sink 端创建AudioTrack成功");
        hashMap.put(62, "Sink 端开始创建音频解码器");
        hashMap.put(63, "Sink 端创建音频解码器成功");
        hashMap.put(64, "Sink 端开始创建视频解码器");
        hashMap.put(65, "Sink 端创建视频解码器成功");
        hashMap.put(66, "Sink 端接收第一帧音频");
        hashMap.put(67, "Sink 端播放第一帧音频");
        hashMap.put(68, "Sink 端接收第一帧视频");
        hashMap.put(69, "Sink 端播放第一帧视频");
        hashMap.put(70, "Sink 端发送终止投屏指令");
        hashMap.put(71, "Sink 端终止投屏指令收到确认回复");
        hashMap.put(72, "Sink 端开始退出");
        hashMap.put(73, "Sink端退出结束");
        hashMap.put(74, "Sink 端开始创建媒体服务");
        hashMap.put(75, "Sink 端媒体服务被连接");
        hashMap.put(76, "Sink 端拉流数据统计");
        hashMap.put(77, "Sink 端视频宽高最终确定");
        hashMap.put(78, "Sink 端申请音频焦点失败");
        hashMap.put(79, "Sink 端获取音频焦点");
        hashMap.put(80, "Sink 端暂时失去音频焦点");
        hashMap.put(81, "Sink 端失去音频焦点");
        hashMap.put(82, "Sink 端UI反控客户端准备就绪");
        hashMap.put(85, "Sink 端视频流Surface可配置");
        hashMap.put(86, "Sink 端视频解码器释放完毕");
    }

    public static String getEventDesc(int i) {
        String str = EVENT_INFO_MAP.get(Integer.valueOf(i));
        if (!TextUtils.isEmpty(str)) {
            return str;
        }
        return "未知事件码:" + i;
    }
}
