package com.upuphone.ar.navi.lite.databinding;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.databinding.ViewDataBinding;
import com.meizu.common.widget.Switch;
import com.upuphone.ar.navi.lite.base.BaseViewModel;
import com.upuphone.ar.navi.lite.view.ActionBarView;

public abstract class ActivitySettingBinding extends ViewDataBinding {
    public final TextView A;
    public final TextView A0;
    public final ConstraintLayout B;
    public final ImageView B0;
    public final Switch C;
    public final TextView C0;
    public final TextView D;
    public final LinearLayout D0;
    public final ConstraintLayout E;
    public final Switch E0;
    public final Switch F;
    public final TextView F0;
    public final TextView G;
    public final ConstraintLayout G0;
    public final TextView H;
    public final Switch H0;
    public final TextView I;
    public BaseViewModel I0;
    public final ImageView J;
    public final ImageView K;
    public final ImageView L;
    public final ImageView M;
    public final ImageView N;
    public final ImageView O;
    public final ImageView P;
    public final TextView Q;
    public final ImageView R;
    public final TextView S;
    public final ConstraintLayout T;
    public final TextView U;
    public final Switch V;
    public final ConstraintLayout W;
    public final ConstraintLayout X;
    public final ConstraintLayout Y;
    public final TextView Z;
    public final ConstraintLayout g0;
    public final Switch h0;
    public final View i0;
    public final TextView j0;
    public final TextView k0;
    public final ConstraintLayout l0;
    public final Switch m0;
    public final TextView n0;
    public final LinearLayout o0;
    public final LinearLayout p0;
    public final TextView q0;
    public final TextView r0;
    public final ConstraintLayout s0;
    public final TextView t0;
    public final Switch u0;
    public final ActionBarView v0;
    public final TextView w0;
    public final ConstraintLayout x0;
    public final Switch y0;
    public final ConstraintLayout z;
    public final LinearLayout z0;

    /* JADX INFO: super call moved to the top of the method (can break code semantics) */
    public ActivitySettingBinding(Object obj, View view, int i, ConstraintLayout constraintLayout, TextView textView, ConstraintLayout constraintLayout2, Switch switchR, TextView textView2, ConstraintLayout constraintLayout3, Switch switchR2, TextView textView3, TextView textView4, TextView textView5, ImageView imageView, ImageView imageView2, ImageView imageView3, ImageView imageView4, ImageView imageView5, ImageView imageView6, ImageView imageView7, TextView textView6, ImageView imageView8, TextView textView7, ConstraintLayout constraintLayout4, TextView textView8, Switch switchR3, ConstraintLayout constraintLayout5, ConstraintLayout constraintLayout6, ConstraintLayout constraintLayout7, TextView textView9, ConstraintLayout constraintLayout8, Switch switchR4, View view2, TextView textView10, TextView textView11, ConstraintLayout constraintLayout9, Switch switchR5, TextView textView12, LinearLayout linearLayout, LinearLayout linearLayout2, TextView textView13, TextView textView14, ConstraintLayout constraintLayout10, TextView textView15, Switch switchR6, ActionBarView actionBarView, TextView textView16, ConstraintLayout constraintLayout11, Switch switchR7, LinearLayout linearLayout3, TextView textView17, ImageView imageView9, TextView textView18, LinearLayout linearLayout4, Switch switchR8, TextView textView19, ConstraintLayout constraintLayout12, Switch switchR9) {
        super(obj, view, i);
        this.z = constraintLayout;
        this.A = textView;
        this.B = constraintLayout2;
        this.C = switchR;
        this.D = textView2;
        this.E = constraintLayout3;
        this.F = switchR2;
        this.G = textView3;
        this.H = textView4;
        this.I = textView5;
        this.J = imageView;
        this.K = imageView2;
        this.L = imageView3;
        this.M = imageView4;
        this.N = imageView5;
        this.O = imageView6;
        this.P = imageView7;
        this.Q = textView6;
        this.R = imageView8;
        this.S = textView7;
        this.T = constraintLayout4;
        this.U = textView8;
        this.V = switchR3;
        this.W = constraintLayout5;
        this.X = constraintLayout6;
        this.Y = constraintLayout7;
        this.Z = textView9;
        this.g0 = constraintLayout8;
        this.h0 = switchR4;
        this.i0 = view2;
        this.j0 = textView10;
        this.k0 = textView11;
        this.l0 = constraintLayout9;
        this.m0 = switchR5;
        this.n0 = textView12;
        this.o0 = linearLayout;
        this.p0 = linearLayout2;
        this.q0 = textView13;
        this.r0 = textView14;
        this.s0 = constraintLayout10;
        this.t0 = textView15;
        this.u0 = switchR6;
        this.v0 = actionBarView;
        this.w0 = textView16;
        this.x0 = constraintLayout11;
        this.y0 = switchR7;
        this.z0 = linearLayout3;
        this.A0 = textView17;
        this.B0 = imageView9;
        this.C0 = textView18;
        this.D0 = linearLayout4;
        this.E0 = switchR8;
        this.F0 = textView19;
        this.G0 = constraintLayout12;
        this.H0 = switchR9;
    }
}
